build script
glific/glific pull request #1117
Opened 2021-02-20 10:23 UTC by pankaj-ag

## Summary

## Test Plan

2021-02-20 13:41 UTC, dlobo requested changes

2021-02-20 13:41 UTC, dlobo commented on build_scripts/staging_build.sh
> +git pull staging master
make staging an argument. so we can use the same script for staging/gigalixir or whatever the person executing it has called those remotes

2021-02-20 13:42 UTC, dlobo requested changes

2021-02-20 13:42 UTC, dlobo commented on build_scripts/staging_build.sh
> +gigalixir ps:ssh -a glific-staging < ./build_scripts/ssh_profile.sh
if migration is requested, (again as an option), we should fire it off, maybe after 3 seconds to give the system time to come up

2021-03-04 10:37 UTC, pankaj-ag commented
We will fix these issues #1207

2021-03-04 10:38 UTC, merged