Feature/contact history
glific/glific pull request #1890
Opened 2021-12-01 13:13 UTC by pankaj-ag

2021-12-02 02:36 UTC, dlobo requested changes

2021-12-02 02:36 UTC, dlobo commented on lib/glific/contacts.ex
> +    end
Why is this needed? since it basically returns the value of Repo.insert?

2021-12-02 02:36 UTC, dlobo commented on lib/glific/contacts.ex
> +        |> case do
Same question as above

2021-12-02 02:36 UTC, dlobo commented on lib/glific/contacts.ex
> +  def capture_history(contact_id, event_type, attrs) when is_integer(contact_id) == true,
== true is redundant?

2021-12-02 02:36 UTC, dlobo commented on lib/glific/contacts.ex
> +    :ok
why not return the value from Repo.insert. we should stop returning :ok and ignore insert results

2021-12-02 02:36 UTC, dlobo commented on lib/glific/flows/action.ex
> +            Contacts.capture_history(context.contact_id, :contact_removed_from_group, %{
ensure that {:ok, _} was returned so we can catch (and die) on the error

2021-12-02 02:36 UTC, dlobo commented on lib/glific/flows/contact_field.ex
> +      event_name: "reset all conatct fields"
spelling mistake

2021-12-02 02:36 UTC, dlobo commented on lib/glific/flows/flow_context.ex
> +      event_name: "all flow stopped for the contact"
we should decide the protocol and style of event name and standardize it

2021-12-07 09:58 UTC, mdshamoon commented
@pankaj-ag feedbacks for contact history:
Link  for design file- [Design file](https://www.sketch.com/s/ba323b85-11d7-4687-8a19-681a32132bab/a/81A5a7)

1. Contact Added to collection -> Update to 'Added to collection: "Collection name in quotes" '
2. Contact Removed to collection -> Update to 'Removed from collection: "Collection name in quotes" '
3. Flow (flow name) started for the contact -> Flow Started  (I can get the flow name from event meta)


![image](https://user-images.githubusercontent.com/32592458/145006677-0042e277-0c1a-45f2-99f5-8c700f2ac54e.png)

2021-12-07 12:08 UTC, merged