Added flow pause and resume functionality
glific/glific pull request #1984
Opened 2022-01-18 13:21 UTC by mdshamoon

## Summary

Added flow pause and resume functionality

## Test Plan

Need to add

2022-01-19 17:37 UTC, dlobo requested changes
Lets chat about overall design and goals

2022-01-19 17:37 UTC, dlobo commented on config/config.exs
> +  {"1 * * * *", Glific.Jobs.MinuteWorker, args: %{job: :wakeup_paused_contacts}},
Might want to merge this with wake_flows cron job

2022-01-19 17:37 UTC, dlobo commented on lib/glific/contacts.ex
> +  Invoked from cron jobs to mass update the flow paused time if the flow is paused for more than three hours
This rule seems fishy? Why 3 hours? whats the reasoning?

2022-01-19 17:37 UTC, dlobo commented on lib/glific/contacts/contact.ex
> +          flows_paused_at: :utc_datetime | nil,
why are we creating a new field instead of just using wakeup time in the context? why should this be a contact field?

2022-01-19 17:37 UTC, dlobo commented on lib/glific/flows/broadcast.ex
> +
we are just starting a broadcast here, why are we checking for paused status? Are we pausing at the contact level?

2022-01-21 10:58 UTC, mdshamoon commented
After our discussion we are starting with the terminate flows first and then think about if we need pause and resume. Closing this favor #1993

2022-01-21 10:58 UTC, closed without merging