speech to text method
glific/glific pull request #2305
Opened 2022-06-21 12:59 UTC by siddhant3030

## Summary
 Google speech to text api

## Checklist
  Before submitting a pull request, please ensure that you mark these task.

- [ ] Ran `mix setup` in the repository root and test.
- [ ] If you've fixed a bug or added code that is tested and has test cases. 
- [ ] In the case of adding a new API, you added a **postman** request for that.
- [ ] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing

## Notes
 Please add here if any other information is required for the reviewer.

2022-06-22 10:00 UTC, pankaj-ag requested changes

2022-06-22 10:00 UTC, pankaj-ag commented on lib/glific/third_party/google_api/google_asr.ex
> +defmodule Glific.GoogleASR do
Let's keep the directory structure consistent 

lib/glific/third_party/ASR/google_asr.ex

2022-06-22 10:00 UTC, pankaj-ag commented on lib/glific/third_party/google_api/google_asr.ex
> +    # IO.inspect(result)
Let's remove this comment

2022-06-22 10:00 UTC, pankaj-ag commented on mix.exs
> +      {:google_api_speech, "~> 0.26"}
Are we using this ?

2022-06-22 10:00 UTC, pankaj-ag commented on lib/glific/third_party/google_api/google_asr.ex
> +        "profanityFilter" => true
can we make language configurable?

2022-06-22 10:00 UTC, pankaj-ag commented on lib/glific/third_party/google_api/google_asr.ex
> +
can you remove this deep indentation and handle by functions?

2022-06-22 16:21 UTC, siddhant3030 commented on mix.exs
> +      {:google_api_speech, "~> 0.26"}
No. I will remove this

2022-06-22 16:21 UTC, siddhant3030 commented on lib/glific/third_party/google_api/google_asr.ex
> +    # IO.inspect(result)
done

2022-06-22 16:21 UTC, siddhant3030 commented on lib/glific/third_party/google_api/google_asr.ex
> +        "profanityFilter" => true
Will look into it.

2022-06-27 13:05 UTC, pankaj-ag commented on lib/glific/third_party/asr/google_asr.ex
> +    token = Partners.get_goth_token(org_id, "google_cloud_storage").token
Let's put a note here that we need to change to google_cloud_asr as a service.

2022-06-27 14:25 UTC, merged