Feature/message converstation
glific/glific pull request #2407
Opened 2022-08-25 15:24 UTC by siddhant3030

## Summary
 Target issue is #2403 
 Explain the **motivation** for making this change. What existing problem does the pull request solve?
 
 message conversation move to big query

## Checklist
  Before submitting a pull request, please ensure that you mark these task.

- [x] Ran `mix setup` in the repository root and test.
- [ ] If you've fixed a bug or added code that is tested and has test cases. 
- [x] In the case of adding a new API, you added a **postman** request for that.
- [x] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing

## Notes
 Please add here if any other information is required for the reviewer.

2022-08-26 12:28 UTC, pankaj-ag requested changes

2022-08-26 12:28 UTC, pankaj-ag commented on lib/glific/third_party/bigquery/bigquery_worker.ex
> +      make_job_to_remove_duplicate("message_conversations", organization_id)
Please remove this. We will not update this table it's just an insert.

2022-08-26 12:41 UTC, siddhant3030 commented on lib/glific/third_party/bigquery/bigquery_worker.ex
> +      make_job_to_remove_duplicate("message_conversations", organization_id)
done

2022-08-29 06:43 UTC, pankaj-ag approved these changes

2022-08-29 07:08 UTC, merged