Dashboard mail
glific/glific pull request #3003
Opened 2023-08-10 09:16 UTC by Darshan2003

## Summary
 Target issue is #2967  

## Notes
 Please add here if any other information is required for the reviewer. 
- Reused the SVGs generated for the live dashboard
- Created a basic structure for sending emails with dashboard graphs
- Working on creating a settings column in the organization table, which would give the frequency of the report to be sent

2023-08-16 15:14 UTC, AkhileshNegi requested changes

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific/communications/mailer.ex
> +  end
@Darshan2003 you can merge both the functions `common_html_send` and `common_send` and pass additional opts to `common_send` as send_html as true and handle it separately

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific/reports.ex
> +      "DAILY" -> day
you can create a single function that matches the period and returns all three things period, start_day and end_day based on that in tuple like {period, start_day, end_day}

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +  <![endif]-->
remove commented code

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
remove commented code

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
remove commented code

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
remove commented code

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
remove commented code

2023-08-16 15:14 UTC, AkhileshNegi commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
remove commented code

2023-08-16 17:57 UTC, Darshan2003 commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +  <![endif]-->
It is a conditional code which will only be rendered only on Outlook mail, It is needed for the mail to be responsive on outlook as well.

For reference: https://webdesign.tutsplus.com/creating-a-future-proof-responsive-email-without-media-queries--cms-23919t

2023-08-17 06:29 UTC, Darshan2003 commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
It is a conditional code which will only be rendered only on Outlook mail, It is needed for the mail to be responsive on outlook as well.

For reference: https://webdesign.tutsplus.com/creating-a-future-proof-responsive-email-without-media-queries--cms-23919t

2023-08-17 06:29 UTC, Darshan2003 commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
It is a conditional code which will only be rendered only on Outlook mail, It is needed for the mail to be responsive on outlook as well.

For reference: https://webdesign.tutsplus.com/creating-a-future-proof-responsive-email-without-media-queries--cms-23919t

2023-08-17 06:30 UTC, Darshan2003 commented on lib/glific_web/templates/dashboard/dashboard.html.heex
> +        <![endif]-->
It is a conditional code which will only be rendered only on Outlook mail, It is needed for the mail to be responsive on outlook as well.

For reference: https://webdesign.tutsplus.com/creating-a-future-proof-responsive-email-without-media-queries--cms-23919t

2023-08-17 06:35 UTC, AkhileshNegi approved these changes

2023-08-17 06:36 UTC, merged