template:generic-template-messages
glific/glific pull request #3029
Opened 2023-08-18 07:21 UTC by AmishaBisht

## Summary
 Target issue is #2783
added a generic function for sending template via expression into the template file.

## Checklist
  Before submitting a pull request, please ensure that you mark these task.

- [ ] Ran `mix setup` in the repository root and test.
- [ ] If you've fixed a bug or added code that is tested and has test cases. 
- [ ] In the case of adding a new API, you added a **postman** request for that.
- [ ] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing

## Notes
 Please add here if any other information is required for the reviewer.

2023-08-18 07:50 UTC, mdshamoon reviewed
Also can you test this in a flow if this is working fine.

2023-08-18 07:50 UTC, mdshamoon commented on lib/glific/templates.ex
> +  def template(template_uuid, variables \\ nil) do
variables will be a list of strings

2023-08-21 05:56 UTC, mdshamoon requested changes

2023-08-21 05:56 UTC, mdshamoon commented on lib/glific/clients/arogya_world.ex
> +  get template form EEx based on  variables
```suggestion
  get template from EEx based on  variables
```

2023-08-21 05:56 UTC, mdshamoon commented on lib/glific/clients/arogya_world.ex
> +  @spec template(integer(), [any()]) :: binary
```suggestion
  @spec template(integer(), [String.t()]) :: binary
```

2023-08-21 05:56 UTC, mdshamoon commented on lib/glific/templates.ex
> +  get template form EEx based on  variables
```suggestion
  get template from EEx based on  variables
```

2023-08-21 05:56 UTC, mdshamoon commented on lib/glific/templates.ex
> +  @spec template(integer(), [any()]) :: binary
```suggestion
  @spec template(integer(), [String.t()]) :: binary
```

2023-08-21 07:39 UTC, AkhileshNegi approved these changes

2023-08-21 07:39 UTC, AkhileshNegi commented on test/glific/templates_test.exs
> +      IO.inspect(assert Templates.template("uuid", ["variable"]) == Jason.encode!(result))
remove inspect

2023-08-21 07:40 UTC, merged