Internal Dashboard: Support for Dashboard Links
glific/glific pull request #3055
Opened 2023-08-25 05:26 UTC by Chaitanya1512

## Summary
 Target issue is #3018

## Notes
 Please add here if any other information is required for the reviewer.

2023-08-26 14:35 UTC, Darshan2003 commented
Follow issue could be:

Not sure why, after adding a few bookmarks and then entering something in the input box after losing the focus from the input box, the text gets cleared automatically.
Not able to regenerate it every time

2023-08-29 10:33 UTC, AkhileshNegi commented
Looks Good, However there is no edit button to edit existing URL if someone enter the wrong URL
You can reference the designs
https://www.figma.com/proto/hvzGlCIQBSwHQ70bsW5m9Z/Web-app?page-id=2%3A2649&type=design&node-id=1136-10808&viewport=-4327%2C-9927%2C0.32&t=p1HdoGl9quCLd3y2-1&scaling=min-zoom

2023-08-29 10:34 UTC, AkhileshNegi requested changes
Please check the comment for designs to add edit option

2023-09-07 07:43 UTC, AkhileshNegi approved these changes

2023-09-07 07:43 UTC, merged