Trigger: show waning when the flow in trigger starts with no hsm  template
glific/glific pull request #3268
Opened 2023-12-21 09:05 UTC by AmishaBisht

## Summary
 Target issue is #3267

while creating the trigger checking if the flow in the trigger is starting with the hsm template or not

2023-12-21 19:17 UTC, mdshamoon requested changes

2023-12-21 19:17 UTC, mdshamoon commented on lib/glific/triggers.ex
> +    end
Why do we need a case statement here?

2023-12-21 19:17 UTC, mdshamoon commented on lib/glific/triggers.ex
> +        {:ok, :no_warnings}
```suggestion
        :ok
```
Why do we need no warnings atom. Just :ok would work

2023-12-21 19:17 UTC, mdshamoon commented on assets/gql/triggers/check_warning.gql
> +mutation CheckTriggerWarnings($input: TriggerInput!) {
```suggestion
mutation ValidateTrigger($input: TriggerInput!) {
```
Update the name in all places

2023-12-21 19:17 UTC, mdshamoon commented on assets/gql/triggers/check_warning.gql
> +    ...ErrorFields
The response format should be the same as publishFlow API
An attribute for success and errors. We don't need the trigger values here

2024-01-02 11:48 UTC, mdshamoon approved these changes
Overall looks good. Just check if this sentence can be more user friendly. Looks weird
<img width="559" alt="image" src="https://github.com/glific/glific/assets/32592458/52f8c425-a88e-4797-b48f-7994aa033165">

2024-01-02 15:12 UTC, AmishaBisht commented
> Overall looks good. Just check if this sentence can be more user friendly <img alt="image" width="559" src="https://private-user-images.githubusercontent.com/32592458/293685332-52f8c425-a88e-4797-b48f-7994aa033165.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMDE5NjUsIm5iZiI6MTcwNDIwMTY2NSwicGF0aCI6Ii8zMjU5MjQ1OC8yOTM2ODUzMzItNTJmOGM0MjUtYTg4ZS00Nzk3LWI0OGYtNzk5NGFhMDMzMTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDEzMjEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMjc1MTQ0ODQ0YWE5ZmFmY2FjOGRkNmQ1MWUzNWVkN2IzNGNlNzMxYTFiYWVjYmQwOGZmMDY5NmM4MjczYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ElVw4ndz2PxHsLhu4sid674SVxVz5QSfzcak7PsrelY">

This warning message came from prod team.

2024-01-03 06:23 UTC, merged