Org status in session response and org status check on loing
glific/glific pull request #3584
Opened 2024-06-03 09:03 UTC by madclaws

## Summary
 Target issue is #_PLEASE_TYPE_ISSUE_NUMBER_

2024-06-06 03:43 UTC, madclaws commented
@kurund @akanshaaa19. I have changed the texts as suggested above.

2024-06-10 15:00 UTC, AkhileshNegi requested changes

2024-06-10 15:00 UTC, AkhileshNegi commented on lib/glific_web/controllers/api/v1/session_controller.ex
> +    with %{status: :active} <- Partners.get_organization!(organization_id),
`
with Organization%{status: :active} <- Partners.get_organization!(organization_id),`

2024-06-11 10:06 UTC, AkhileshNegi approved these changes

2024-06-11 10:07 UTC, merged