allowTemplateChange
glific/glific pull request #3598
Opened 2024-06-10 11:48 UTC by aashi-ihsaa

## Summary
 Target issue is #3553 
 Explain the **motivation** for making this change. What existing problem does the pull request solve?
Changes the API so that it can accept either `True` or `False` value for `allowTemplateCategoryChange`.

## Notes
 Please add here if any other information is required for the reviewer.

2024-06-10 14:58 UTC, AkhileshNegi requested changes

2024-06-10 14:58 UTC, AkhileshNegi commented on lib/glific/providers/gupshup/partner/partner_api.ex
> +      |> Map.put_new("allowTemplateCategoryChange", true)
u need to update the API as well

2024-06-12 07:31 UTC, AmishaBisht requested changes
You are already passing the default value as true in `Map.get(attrs, :allow_template_category_change, true)`, so there is no need to pass it again in allow_category_change \\ true`

2024-06-19 21:07 UTC, AmishaBisht approved these changes

2024-06-20 04:33 UTC, merged