Auto trans/export import
glific/glific pull request #3602
Opened 2024-06-12 12:37 UTC by AmishaBisht

## Summary
 Target issue is #_PLEASE_TYPE_ISSUE_NUMBER_  
 Explain the **motivation** for making this change. What existing problem does the pull request solve?

## Checklist
  Before submitting a pull request, please ensure that you mark these task.

- [ ] Ran `mix setup` in the repository root and test.
- [ ] If you've fixed a bug or added code that is tested and has test cases. 
- [ ] In the case of adding a new API, you added a **postman** request for that.
- [ ] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing

## Notes
 Please add here if any other information is required for the reviewer.

2024-06-20 15:31 UTC, madclaws commented on test/glific/interactive_templates_test.exs
> +  test "export the interactive template",
Can we have tests for interactive_message_type "list" and "location_request_message"

2024-06-20 15:34 UTC, AkhileshNegi requested changes

2024-06-20 15:34 UTC, AkhileshNegi commented on lib/glific/templates/interactive_templates.ex
> +  defp build_item_rows(translations, language_codes, id) do
missing spec

2024-06-20 15:34 UTC, AkhileshNegi commented on lib/glific/templates/interactive_templates.ex
> +  defp build_quick_reply_csv_data(translations, language_codes, id) do
missing spec

2024-06-20 15:56 UTC, madclaws commented on test/glific/interactive_templates_test.exs
> +  end
Do we have a test where content with caption field, if not can we add that too, since we have some extra code regarding that.

2024-06-20 16:02 UTC, madclaws commented on lib/glific/templates/interactive_templates.ex
> +  defp build_quick_reply_csv_data(translations, language_codes, id) do
can we add specs here?

2024-06-20 16:02 UTC, madclaws commented on lib/glific/templates/interactive_templates.ex
> +  defp build_quick_reply_csv_body(translations, language_codes, id) do
can we add specs here?

2024-06-20 16:02 UTC, madclaws commented on lib/glific/templates/interactive_templates.ex
> +  defp build_quick_reply_options(translations, language_codes, id) do
can we add specs here?

2024-06-21 03:39 UTC, madclaws approved these changes

2024-06-21 04:05 UTC, merged