Automated Account Setup
glific/glific pull request #3694
Opened 2024-07-23 21:32 UTC by vgull574

Target Issue is #3679 

Created function that generates password and hashes it via Ecto
Created separate public function that takes an organization id and generates a hashed password and updates that password in the user table

2024-07-26 03:42 UTC, madclaws requested changes

2024-07-26 03:42 UTC, madclaws commented on lib/glific/misc/password.ex
> +    Logger.info("Generated and hashed password successfully.")
We don't need to Log anything here, can we remove this?

2024-07-26 03:43 UTC, madclaws requested changes

2024-07-26 03:43 UTC, madclaws commented on lib/glific/saas/onboard.ex
> +  def update_process_on_submission(org_id) do
Can we rename this function, since it focus on updating the password of NGO account

2024-07-26 03:43 UTC, madclaws commented on lib/glific/saas/onboard.ex
> +    now = DateTime.utc_now()
Also we need to add test for this function.

2024-08-13 12:42 UTC, madclaws approved these changes

2024-08-13 12:42 UTC, madclaws commented on lib/glific/saas/onboard.ex
> +
can we add Glific.Repo.put_process_state(org_id)

2024-08-13 12:42 UTC, merged

2024-08-13 15:17 UTC, dlobo reviewed
Why oh why oh why, do we even think about writing password generators