Feat/new webhook geocode
glific/glific pull request #3713
Opened 2024-08-07 03:33 UTC by aharshal623

## Summary
 Target issue is #3616 
This PR is the first attempt at taking on the PRD for reverse geocoding. In this PR, we use the Google Maps API to return city, state, country, etc. for a given lat/long. Additionally, we implemented functionality for the API key to be taken from .env.dev and not be publicly exposed.

## Checklist
  Before submitting a pull request, please ensure that you mark these task.

- [ ] Ran `mix setup` in the repository root and test.
- [ ] If you've fixed a bug or added code that is tested and has test cases. 
- [ ] In the case of adding a new API, you added a **postman** request for that.
- [ ] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing

## Notes
 Please add here if any other information is required for the reviewer.

2024-08-08 15:40 UTC, madclaws requested changes

2024-08-08 15:40 UTC, madclaws commented on lib/glific/clients/common_webhook.ex
> +  defp find_component(components, type) do
Can we add function spec here?

2024-08-08 15:40 UTC, madclaws commented on lib/glific/clients/common_webhook.ex
> +  def webhook("geolocation", fields) do
Can we add test case for this function?

2024-08-08 15:41 UTC, madclaws commented
Can you also fix the credo warnings @aharshal623

2024-08-16 03:52 UTC, AkhileshNegi requested changes

2024-08-16 03:52 UTC, AkhileshNegi commented on lib/glific/communications/message.ex
> -    Logger.info("Received message: type: '#{type}', id: '#{message_params[:bsp_message_id]}'")
can you revert these changes and take the latest pull

2024-08-16 03:52 UTC, AkhileshNegi commented on lib/glific/communications/wa_group_message.ex
> -    Logger.info("Received message: type: '#{type}', id: '#{message_params[:bsp_id]}'")
can you revert these changes and take the latest pull

2024-08-16 03:52 UTC, AkhileshNegi commented on test/glific/flows/webhook_test.exs
> +    assert result[:address] != nil
can u match the actual values rather than matching not nil

2024-08-16 12:51 UTC, madclaws commented on test/glific/flows/webhook_test.exs
> +    assert result[:success] == false
you can use `refute result[:success]` instead of this line.

2024-08-16 12:52 UTC, madclaws commented on test/glific/flows/webhook_test.exs
> +    assert result[:error] != nil
can use `is_nil`

2024-08-21 03:45 UTC, madclaws requested changes

2024-08-21 03:45 UTC, madclaws commented on lib/glific/clients/common_webhook.ex
> +    |> then(&((&1 && &1["long_name"]) || "N/A"))
Can we make this simple, it looks way cryptic for reading. @aharshal623

2024-08-22 05:33 UTC, madclaws approved these changes

2024-08-22 05:34 UTC, merged