Created functions for assistants and vector stores
glific/glific pull request #3714
Opened 2024-08-07 06:07 UTC by vgull574

Target issue is #3689
 
Created functions to create/delete vector stores and assistants to implement file search.

2024-08-16 04:16 UTC, AkhileshNegi requested changes

2024-08-16 04:16 UTC, AkhileshNegi commented on lib/glific_web/resolvers/openai.ex
> +    do: ChatGPT.delete_vector_store(vector_store_id)
Instead of ChatGPT can you create a separate file in the same directory named openai and module name `Glific.OpenAI`
`lib/glific/third_party/openAI`
As vector store and assistant is more of a openAI offering than within ChatGPT

2024-08-16 04:16 UTC, AkhileshNegi commented on lib/glific_web/resolvers/openai.ex
> +    do: ChatGPT.create_vector_store(name)
same here

2024-08-16 04:16 UTC, AkhileshNegi commented on lib/glific_web/resolvers/openai.ex
> +    do: ChatGPT.create_assistant(args)
same here

2024-08-16 04:16 UTC, AkhileshNegi commented on lib/glific_web/resolvers/openai.ex
> +    do: ChatGPT.delete_assistant(assistant_id)
same here

2024-08-16 04:16 UTC, AkhileshNegi commented on lib/glific/third_party/openAI/chatGPT.ex
> +    ]
this line is repeated 4 times in this PR can you create a function for same and optimise the code

2024-09-20 12:02 UTC, madclaws commented
Closing this PR, since #3744 is an extension of this.

2024-09-20 12:02 UTC, closed without merging