Template flows: Adding the template flows in seeder
glific/glific pull request #3760
Opened 2024-08-25 17:43 UTC by AmishaBisht

## Summary
 Target issue is #_PLEASE_TYPE_ISSUE_NUMBER_  
 Explain the **motivation** for making this change. What existing problem does the pull request solve?

## Checklist
  Before submitting a pull request, please ensure that you mark these task.

- [ ] Ran `mix setup` in the repository root and test.
- [ ] If you've fixed a bug or added code that is tested and has test cases. 
- [ ] In the case of adding a new API, you added a **postman** request for that.
- [ ] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing

## Notes
 Please add here if any other information is required for the reviewer.

2024-09-18 14:57 UTC, madclaws requested changes

2024-09-18 14:57 UTC, madclaws commented on lib/glific/seeds/seeds_flows.ex
> +    Enum.each(flow_files, &process_flow_file(&1, organizations))
`Enum.each` already returns :ok

2024-09-18 14:57 UTC, madclaws commented on lib/glific/seeds/seeds_flows.ex
> +      _ ->
Can we add a Log here, will be useful in case flow import failed

2024-09-18 14:57 UTC, madclaws commented on lib/glific/seeds/seeds_migration.ex
> +  defp do_migrate_data(:template, organizations), do: SeedsFlows.add_template_flows(organizations)
Shouldn't we add `migrate_data(:template, organization)` in `seeds/20200723172939_add_glific_data.exs`, so that it will work for new orgs?

2024-09-18 14:57 UTC, madclaws commented on priv/data/flows/geolocation.json
> +                                "text": "Location details\n\nWard - @results.loc.ward\nState - @results.loc.state\nPostal Code - @results.loc.postal_code\nDistrict - @results.loc.district\nCity - @re
We have removed `ward` from the location results. So can we remove that from this flow too?
https://github.com/glific/glific/pull/3814

2024-09-22 17:52 UTC, AmishaBisht commented
To test the PR and add the new templates for an org we can run the commands in iex:
```org = Glific.Partners.get_organization!(org_id)```
```Glific.Seeds.SeedsMigration. migrate_data(:template_flows, org)```

2024-09-23 05:17 UTC, madclaws approved these changes

2024-09-23 05:18 UTC, merged