optimize organization info subscriptions
glific/glific pull request #879
Opened 2021-01-06 11:13 UTC by AkhileshNegi

2021-01-06 17:33 UTC, dlobo requested changes
We should update the last_communication at via a trigger in the DB and not via code. We already update this field via a trigger in the messages table.

Ping me if needed and I can show you where the code is. You'll just need to extend the same trigger

2021-01-07 05:10 UTC, pankaj-ag commented
@AkhileshNegi can you please move all your changes related to the last communication to a different PR.

2021-01-07 11:34 UTC, pankaj-ag approved these changes

2021-01-07 11:34 UTC, pankaj-ag commented on priv/repo/migrations/20200615073630_add_message_number_to_messages.exs
> +        UPDATE organizations set last_communication_at = (CURRENT_TIMESTAMP at time zone 'utc') where id = NEW.organization_id;
@AkhileshNegi please test. I think this will break since there is no last_communication_at column at that time?

2021-01-07 11:34 UTC, merged